/**
 * QBA Customer Service Agent — post-purchase support for QBA product customers
 */
(function(){
if(window.__QBA_CS)return;window.__QBA_CS=true;
const CSS=`#qcs-btn{position:fixed;bottom:96px;right:24px;z-index:999997;width:50px;height:50px;border-radius:50%;background:#22c55e;color:#000;border:none;cursor:pointer;font-size:22px;box-shadow:0 4px 20px rgba(34,197,94,.35);display:flex;align-items:center;justify-content:center}#qcs-btn:hover{transform:scale(1.1)}#qcs-win{position:fixed;bottom:156px;right:24px;z-index:999996;width:380px;max-width:calc(100vw-48px);max-height:500px;height:60vh;background:#0f0f1a;border:1px solid #1a1a2e;border-radius:16px;display:none;flex-direction:column;overflow:hidden}#qcs-h{padding:14px;background:linear-gradient(135deg,#0f0f1a,#1a1a2e);border-bottom:1px solid #1a1a2e;display:flex;align-items:center;gap:10px}#qcs-h .av{font-size:28px}#qcs-h .nf{flex:1}#qcs-h .nm{color:#fff;font-weight:700;font-size:14px}#qcs-h .sb{color:#94a3b8;font-size:10px}#qcs-h .cl{background:none;border:none;color:#555;font-size:18px;cursor:pointer}#qcs-ms{flex:1;overflow-y:auto;padding:12px;display:flex;flex-direction:column;gap:6px}.qcm{max-width:88%;padding:10px 14px;border-radius:12px;font-size:12px;line-height:1.6}.qcm.b{background:#1a1a25;color:#e2e8f0;align-self:flex-start;border-bottom-left-radius:4px}.qcm.u{background:#22c55e;color:#000;align-self:flex-end;border-bottom-right-radius:4px}#qcs-in{padding:10px;border-top:1px solid #1a1a2e;display:flex;gap:6px;background:#0a0a0f}#qcs-in input{flex:1;background:#1a1a25;border:1px solid #2a2a3e;border-radius:8px;padding:8px 12px;color:#fff;font-size:12px;outline:none}#qcs-in input:focus{border-color:#22c55e}#qcs-in button{background:#22c55e;color:#000;border:none;border-radius:8px;padding:8px 14px;font-weight:700;cursor:pointer;font-size:12px}#qcs-ft{text-align:center;padding:6px;font-size:8px;color:#333;border-top:1px solid #0f0f1a}`;
document.head.appendChild(Object.assign(document.createElement('style'),{textContent:CSS}));
const btn=document.createElement('div');btn.id='qcs-btn';btn.innerHTML='🎧';btn.title='Customer Support';document.body.appendChild(btn);
const w=document.createElement('div');w.id='qcs-win';
w.innerHTML='<div id="qcs-h"><div class="av">🎧</div><div class="nf"><div class="nm">QBA Support</div><div class="sb">Post-purchase · 24/7 · <30s SLA</div></div><button class="cl" onclick="qcsT()">✕</button></div><div id="qcs-ms"></div><div id="qcs-in"><input id="qcs-i" placeholder="Need help with your subscription?"/><button onclick="qcsS()">Send</button></div><div id="qcs-ft">⚡ Quantum Bots Agency</div>';
document.body.appendChild(w);
let op=false;window.qcsT=function(){op=!op;w.style.display=op?'flex':'none';btn.style.display=op?'none':'flex';if(op&&!window.__qcsS){window.__qcsS=true;setTimeout(()=>{const m=document.getElementById('qcs-ms');const d=document.createElement('div');d.className='qcm b';d.innerHTML="👋 Welcome to QBA Support!\n\nAlready a customer? I can help with:\n\n• 💳 **Billing** — invoices, payment issues, receipts\n• 🔧 **Setup help** — installation guides, API keys\n• ⚠️ **Issues** — bugs, errors, feature requests\n• 📋 **Account** — upgrades, cancellations, plan changes\n\nJust describe what you need and I'll help!";m.appendChild(d)}),600}};
btn.onclick=window.qcsT;
window.qcsS=function(){const i=document.getElementById('qcs-i');const t=i.value.trim();if(!t)return;i.value='';const m=document.getElementById('qcs-ms');const d=document.createElement('div');d.className='qcm u';d.textContent=t;m.appendChild(d);m.scrollTop=m.scrollHeight;setTimeout(()=>{const r=document.createElement('div');r.className='qcm b';r.innerHTML="📝 I've noted your request. For immediate help:\n\n📧 support@quantumbotsagency.com\n⏱ Average response <30 seconds\n\nA human agent will follow up if needed.";m.appendChild(r);m.scrollTop=m.scrollHeight},800)};
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&document.activeElement&&document.activeElement.id==='qcs-i')qcsS()});
})();
