(function(){
if(window.__QBA_AGENT)return;window.__QBA_AGENT=true;
const css=`#qba-agent-btn{position:fixed;bottom:24px;right:24px;z-index:999999;width:60px;height:60px;border-radius:50%;background:#818cf8;color:#000;border:none;cursor:pointer;font-size:28px;box-shadow:0 4px 24px rgba(129,140,248,.4);display:flex;align-items:center;justify-content:center}#qba-agent-btn:hover{transform:scale(1.1)}#qba-agent-window{position:fixed;bottom:96px;right:24px;z-index:999998;width:380px;max-width:calc(100vw-48px);max-height:600px;height:70vh;background:#0f0f1a;border:1px solid #1a1a2e;border-radius:16px;display:none;flex-direction:column;overflow:hidden}#qba-ah{padding:16px;background:linear-gradient(135deg,#0f0f1a,#1a1a2e);border-bottom:1px solid #1a1a2e;display:flex;align-items:center;gap:12px}#qba-ah .av{font-size:32px}#qba-ah .nm{color:#fff;font-weight:700;font-size:15px}#qba-ah .sub{color:#94a3b8;font-size:11px}#qba-ah .cl{background:none;border:none;color:#555;font-size:20px;cursor:pointer}#qba-am{flex:1;overflow-y:auto;padding:16px;display:flex;flex-direction:column;gap:8px}#qba-ai{d padding:12px;border-top:1px solid #1a1a2e;display:flex;gap:8px;background:#0a0a0f}#qba-ai input{flex:1;background:#1a1a25;border:1px solid #2a2a3e;border-radius:8px;padding:10px 14px;color:#fff;font-size:13px;outline:none}#qba-ai input:focus{border-color:#818cf8}#qba-ai button{background:#818cf8;color:#000;border:none;border-radius:8px;padding:10px 18px;font-weight:700;cursor:pointer;font-size:13px}#qba-af{text-align:center;padding:8px;font-size:9px;color:#333;border-top:1px solid #0f0f1a}#qba-af a{color:#555;text-decoration:none}.qm{max-width:85%;padding:10px 14px;border-radius:12px;font-size:13px;line-height:1.6}.qm.b{background:#1a1a25;color:#e2e8f0;align-self:flex-start;border-bottom-left-radius:4px}.qm.u{background:#818cf8;color:#000;align-self:flex-end;border-bottom-right-radius:4px}.qty{display:flex;gap:4px;padding:10px 14px;background:#1a1a25;border-radius:12px;align-self:flex-start}.qty span{width:6px;height:6px;background:#555;border-radius:50%;animation:qb 1.4s infinite}.qty span:nth-child(2){animation-delay:.2s}.qty span:nth-child(3){animation-delay:.4s}@keyframes qb{0%,60%,100%{transform:translateY(0)}30%{transform:translateY(-4px)}}`;
document.head.appendChild(Object.assign(document.createElement('style'),{textContent:css}));

const btn=document.createElement('div');btn.id='qba-agent-btn';btn.innerHTML='⚡';btn.onclick=toggle;
const pulse=document.createElement('span');Object.assign(pulse.style,{position:'absolute',width:'100%',height:'100%',borderRadius:'50%',border:'2px solid #818cf8',animation:'qb 2s infinite',opacity:'0'});btn.appendChild(pulse);
document.body.appendChild(btn);

const w=document.createElement('div');w.id='qba-agent-window';
w.innerHTML='<div id="qba-ah"><div class="av">⚡</div><div class="info"><div class="nm">QBA Sales Agent</div><div class="sub">AI Products · 24/7 · Quantum Bots Agency</div></div><button class="cl" onclick="qt()">✕</button></div><div id="qba-am"></div><div id="qba-ai"><input id="qi" placeholder="Ask about any of our 100 AI products..."/><button onclick="qs()">Send</button></div><div id="qba-af"><a href="https://quantumbotsagency.com" target="_blank">⚡ Quantum Bots Agency — 100 AI Products</a></div>';
document.body.appendChild(w);

let open=false;
function toggle(){open=!open;w.style.display=open?'flex':'none';btn.style.display=open?'none':'flex';if(open&&!window.__qaaS){window.__qaaS=true;setTimeout(()=>{addB("👋 Hi! Welcome to **Quantum Bots Agency**.\n\nI can help you find the perfect AI product from our **100-product catalog**. What kind of tool are you looking for?")},500);setTimeout(()=>addB("💡 **Quick categories:**\n• 🤖 Core Bots\n• ✍️ Content Creation\n• 🎯 Marketing & Sales\n• 🔍 Research & Intel\n• 💼 Support & Service\n• 🔗 Integrations\n• 🛡️ Security\n• 📊 Analytics\n• ⚙️ Operations"),1500)}}
function addB(t){const m=document.getElementById('qba-am');const d=document.createElement('div');d.className='qm b';d.textContent=t;m.appendChild(d);m.scrollTop=m.scrollHeight}
function addU(t){const m=document.getElementById('qba-am');const d=document.createElement('div');d.className='qm u';d.textContent=t;m.appendChild(d);m.scrollTop=m.scrollHeight}
window.qt=toggle;window.qs=function(){const i=document.getElementById('qi');const t=i.value.trim();if(!t)return;i.value='';addU(t);setTimeout(()=>addB("Great question! Here are our best matching products for that. Check our catalog at **quantumbotsagency.com/products/** or browse by category on our homepage."),800)};document.addEventListener('keydown',e=>{if(e.key==='Enter'&&document.activeElement&&document.activeElement.id==='qi')qs()});
})();
